name: Build MYR

on: [push, pull_request]

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    container:
      image: node:10.13
    
    steps:
      - uses: actions/checkout@v1
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Fetch packages
        run: yarn install
      - name: Build production build
        run: yarn build